height_factor <- factor(women$height)
print("Height Factor:")
print(height_factor)
print("Levels of Height Factor:")
print(levels(height_factor))

set.seed(123)
char_sample <- sample(LETTERS, size = 20, replace = TRUE)
factor_sample <- factor(char_sample)
print("Sampled Letters Factor:")
print(factor_sample)
print("Levels:")
print(levels(factor_sample))
print("Frequency Table:")
print(table(factor_sample))